---
- hosts: localhost
  become: false
  tasks:
    - name: Install packages
      become: true
      ansible.builtin.apt:
        pkg:
          - btop
          - cmake
          - flameshot
          - gcc
          - git
          - htop
          - lolcat
          - make
          - mc
          - ncdu
          - neovim
          - npm
          - openssh-server
          - podman
          - python3
          - python3-pip
          - ranger
          - remmina
          - tmux
          - tcptrack
          - terminator
          - toilet
          - ufw
          - vim
          - vlc
          - xrdp
          - zsh

    - name: Set login shell of user {{ login_user }} to `zsh` with `usermod`
      ansible.builtin.command: usermod --shell /usr/bin/zsh {{ login_user }}
      become: true
      changed_when: false

    - name: Setup ZSH
      ansible.builtin.copy:
        src: zsh/.zshrc
        dest: ~/.zshrc
