- hosts: localhost
  become: false
  tasks:
    - name: Sync packages
      become: true
      ansible.builtin.package:
        name:
          - cmake
          - gcc
          - git
          - htop
          - make
          - mc
          - ncdu
          - openssh-server
          - python3
          - python3-pip
          - tmux
          - vim
          - zsh

    - name: set zsh as the main shell
      ansible.builtin.command: usermod --shell /usr/bin/zsh {{ ansible_user_id }}
      become: true
      changed_when: false

    - name: Check if Oh My Zsh installed
      stat:
        path: "{{ ansible_env.HOME }}/.oh-my-zsh"
      register: omz_installed

    - name: download ansible installer
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
        dest: /tmp/install_omz.sh
        mode: '0755'
      when: not omz_installed.stat.exists

    - name: install omz
      ansible.builtin.command: /tmp/install_omz.sh
      when: not omz_installed.stat.exists

    - name: copy zshrc
      ansible.builtin.copy:
        src: zsh/.zshrc
        dest: /home/{{ ansible_user_id }}/.zshrc
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
        mode: '0644'

    - name: copy vimrc
      ansible.builtin.copy:
        src: vim/.vimrc
        dest: /home/{{ ansible_user_id }}/.vimrc
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
        mode: '0644'

