---

- hosts: localhost
  become: false
  tasks:
  - name: Sync packages
    become: true
    ansible.builtin.package:
        name:
          - cmake
          - gcc
          - git
          - htop
          - make
          - mc
          - ncdu
          - openssh-server
          - python3
          - python3-pip
          - tmux
          - vim
          - zsh

  - name: set zsh as the main shell
    ansible.builtin.command: usermod --shell /usr/bin/zsh {{ ansible_user_id }}
    become: true
    changed_when: false

  - name: copy zshrc
    ansible.builtin.copy:
        src: zsh/.zshrc
        dest: /home/{{ ansible_user_id }}/.zshrc
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
        mode: '0644'

